# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `simplecov-html` gem.
# Please instead update this file by running `bin/tapioca gem simplecov-html`.

# typed: true

module SimpleCov
  extend ::SimpleCov::Configuration

  class << self
    def add_not_loaded_files(result); end
    def clear_result; end
    def exit_exception; end
    def exit_status_from_exception; end
    def filtered(files); end
    def grouped(files); end
    def load_adapter(name); end
    def load_profile(name); end
    def pid; end
    def pid=(_arg0); end
    def process_result(result, exit_status); end
    def result; end
    def result?; end
    def result_exit_status(result, covered_percent); end
    def run_exit_tasks!; end
    def running; end
    def running=(_arg0); end
    def set_exit_exception; end
    def start(profile = T.unsafe(nil), &block); end
    def usable?; end
    def write_last_run(covered_percent); end
  end
end

module SimpleCov::Formatter; end

class SimpleCov::Formatter::HTMLFormatter
  def format(result); end
  def output_message(result); end

  private

  def asset_output_path; end
  def assets_path(name); end
  def coverage_css_class(covered_percent); end
  def formatted_file_list(title, source_files); end
  def formatted_source_file(source_file); end
  def id(source_file); end
  def link_to_source_file(source_file); end
  def output_path; end
  def shortened_filename(source_file); end
  def strength_css_class(covered_strength); end
  def template(name); end
  def timeago(time); end
end

SimpleCov::Formatter::HTMLFormatter::VERSION = T.let(T.unsafe(nil), String)
SimpleCov::VERSION = T.let(T.unsafe(nil), String)
